In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Install necessary libraries
!pip install transformers
!pip install adapter-transformers
!pip install torch
!pip install datasets
!pip install webdataset
!pip install pytorch_lightning
!pip install git+https://github.com/openai/CLIP.git
# download the linear mse model path
!wget https://github.com/microsoft/LMOps/raw/main/promptist/aesthetic/sac%2Blogos%2Bava1-l14-linearMSE.pth
!pip install openai
!pip install hpsv2
!pip install diffusers

In [ ]:
!pip install adapter-transformers -U

  Using cached tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.15.0
    Uninstalling tokenizers-0.15.0:
      Successfully uninstalled tokenizers-0.15.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.35.2 requires tokenizers<0.19,>=0.14, but you have tokenizers 0.13.3 which is incompatible.


In [ ]:
import sys
sys.path.append('/content/drive/Shared drives/capstone_rlt2i/codes/reward_predictor/aesthetic_scores/')
import simple_inference_custom

In [ ]:
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import random
# simple_inference_custom is the customized script we have to calcualte aesthetic score
from simple_inference_custom import predict_aesthetic_score
import torch
import os
import hpsv2
from sklearn.preprocessing import MinMaxScaler
from transformers import CLIPProcessor, CLIPModel
from datasets import load_dataset
import numpy as np
import openai
import json
import os
from pathlib import Path
from base64 import b64decode

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
# policy model as an actor-critic model
class PolicyModel(nn.Module):
    def __init__(self, prompt_feature_size):
        super(PolicyModel, self).__init__()
        self.fc1 = nn.Linear(prompt_feature_size, 128)
        self.fc2 = nn.Linear(128, 64)

        # Actor layer for temperature
        self.fc_actor_temp = nn.Linear(64, 1)

        # Critic layer
        self.fc_critic = nn.Linear(64, 1)

        self.sigmoid = nn.Sigmoid()

    def forward(self, prompt_features):
        # Ensure prompt_features is a 2D tensor
        if len(prompt_features.size()) == 1:
            prompt_features = prompt_features.unsqueeze(0)
        x = torch.relu(self.fc1(prompt_features))
        x = torch.relu(self.fc2(x))

        # Actor output for temperature
        temperature = self.sigmoid(self.fc_actor_temp(x))

        # Critic output
        # value_estimate = self.fc_critic(x)
        # Added sigmoid activation to limit prediction value within 0 and 1
        value_estimate = self.sigmoid(self.fc_critic(x))

        return temperature, value_estimate

    def initialize_with_defaults(self, default_temperature=0.9):
        # For temperature: Using the sigmoid's inverse to get the pre-activation value
        temp_bias = -torch.log(1. / torch.tensor(default_temperature) - 1.)
        self.fc_actor_temp.bias.data.fill_(temp_bias.item())

In [ ]:
import pandas as pd

In [ ]:
training_data_path = '/content/drive/Shared drives/capstone_rlt2i/Momo/'
training_data = pd.read_csv(training_data_path+'finetuning-dataset.csv')
df_data_samples_evaluation = training_data[5000: 5300]

In [ ]:
df_data_samples_evaluation.head()

Base_prompt  \
5000  of the dark jungle with large strange scary cr...   
5001                                   portrait of apex   
5002             hyperrealistic portrait of a cyberpunk   
5003                       beautiful female ginger hair   
5004                            2 8 mm closeup portrait   

                                                 Prompt  
5000  of the dark jungle with large strange scary cr...  
5001  portrait of apex legends naomi campbell, intri...  
5002  hyperrealistic portrait of a cyberpunk man, lo...  
5003  beautiful female ginger hair glasses symmetric...  
5004  2 8 mm closeup portrait of a beautiful bettie ...

In [ ]:
YOUR_PROMPT_FEATURE_SIZE = 768
print("text feature size: ", YOUR_PROMPT_FEATURE_SIZE)

text feature size:  768


In [ ]:
# iniatilization for temperatures, prompt length, and RL agent parameters
DEFAULT_TEMPERATURE = 0.9
EPSILON = 0.9
EPSILON_DECAY = 0.995
LEARNING_RATE = 0.001

loaded_policy_model = PolicyModel(prompt_feature_size=YOUR_PROMPT_FEATURE_SIZE)
loaded_policy_model.to(device)

PolicyModel(
  (fc1): Linear(in_features=768, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc_actor_temp): Linear(in_features=64, out_features=1, bias=True)
  (fc_critic): Linear(in_features=64, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [ ]:
# Initialize the model architecture
# policy_model = PolicyModel(prompt_feature_size=YOUR_PROMPT_FEATURE_SIZE)

# Load the state dictionary
checkpoint_file_path = "/content/drive/Shared drives/capstone_rlt2i/Momo/final_model/policy_model_checkpoint.pth"
checkpoint = torch.load(checkpoint_file_path)
loaded_policy_model.load_state_dict(checkpoint['model_state_dict'])

# Set the model to evaluation mode
loaded_policy_model.eval()

PolicyModel(
  (fc1): Linear(in_features=768, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (fc_actor_temp): Linear(in_features=64, out_features=1, bias=True)
  (fc_critic): Linear(in_features=64, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [ ]:
import torch
from transformers import BertModel, BertTokenizer

# function to extract text features
def extract_bert_features(row):
    text = row['Base_prompt']

    # Load the BERT model and tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased').to(device)

    # Tokenize the text and truncate/pad it to the maximum length
    inputs = tokenizer(text, return_tensors="pt", max_length=512, truncation=True, padding="max_length").to(device)

    # Extract text features
    with torch.no_grad():
        outputs = model(**inputs)
        # You can use the pooled output or the last hidden states depending on your preference
        text_features = outputs.pooler_output

    return text_features.to('cpu')

In [ ]:
from diffusers import StableDiffusionPipeline

t2i_pipe = StableDiffusionPipeline.from_pretrained("prompthero/openjourney", torch_dtype=torch.float32)
t2i_pipe = t2i_pipe.to(device)

In [ ]:
# text to image generation
# use openjourney text to image model
def text_to_image_generation(prompts):
    images = t2i_pipe(prompts).images
    return images

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "meta-llama/Llama-2-7b-chat-hf"
access_token = "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"

LM_tokenizer = AutoTokenizer.from_pretrained(model_name, token=access_token)
LM_model = AutoModelForCausalLM.from_pretrained(model_name, token=access_token)

# Set the model to evaluation mode
LM_model.eval()

In [ ]:
few_shot_prompts = (LM_tokenizer.bos_token + "Base prompt: a green hair guy\nEnriched prompt for text-to-image generation: a highly detailed portrait of a man with dark green hair and green glowing eyes, high detail clothing, concept art, anime, artstation, professional."+ LM_tokenizer.eos_token
    + "\n" + LM_tokenizer.bos_token + "Base prompt: animal crossing werewolf\nEnriched prompt for text-to-image generation: a cute chibi werewolf animal crossing villager. animal crossing character. 3 d render, 3 d model, simplified, animal crossing new horizons, hq, arstation."+ LM_tokenizer.eos_token
    + "\n" + LM_tokenizer.bos_token + "Base prompt: an android woman\nEnriched prompt for text-to-image generation: portrait of a beautiful android woman, futuristic, chrome and colorful, photo realistic, ray tracing, 3 d shading, octane render."+ LM_tokenizer.eos_token
)

few_shot_prompt_encoded = LM_tokenizer.encode(few_shot_prompts, return_tensors='pt')[0]

In [ ]:
def prompt_enrichment(prompt, temperature=0.5, desired_length=300):
    curr_prompt = "Base prompt: " + prompt + "\nEnriched prompt for text-to-image generation: "

    # Tokenize the prompt
    curr_prompt_encoded = LM_tokenizer.encode("\n" + LM_tokenizer.bos_token + curr_prompt, return_tensors='pt')[0]
    input_ids = torch.cat((few_shot_prompt_encoded, curr_prompt_encoded), dim=0)

    # Generate text with temperature and desired length
    output = LM_model.generate(input_ids.unsqueeze(0), max_length=desired_length, num_return_sequences=1, bos_token_id=LM_tokenizer.bos_token_id,
                            eos_token_id=LM_tokenizer.eos_token_id, temperature=temperature, do_sample=True)

    # Decode the generated text
    generated_text = LM_tokenizer.decode(output[0], skip_special_tokens=True)

    # Remove possible unwanted text
    start_idx = generated_text.find(curr_prompt)
    if start_idx != -1:
        generated_text = generated_text[start_idx + len(curr_prompt):]

    end_idx = generated_text.find("\n")
    if end_idx != -1:
        generated_text = generated_text[:end_idx]

    end_idx = generated_text.find("Base prompt")
    if end_idx != -1:
        generated_text = generated_text[:end_idx]

    generated_text = generated_text.strip()

    return generated_text

In [ ]:
# Define the function to perform inference
def perform_inference(initial_prompt):
    # Extract text features from the initial prompt
    text_features = extract_bert_features(initial_prompt).to(device)


    # Predict the temperature using the loaded policy model
    with torch.no_grad():
        predicted_temperature, _ = loaded_policy_model(text_features)

    # Use the predicted temperature for prompt enrichment
    enriched_prompt = prompt_enrichment(initial_prompt, temperature=predicted_temperature.item())

    # Perform text-to-image generation using the enriched prompt
    generated_image = text_to_image_generation(enriched_prompt)

    return enriched_prompt, generated_image, predicted_temperature.item()

In [ ]:
# Example usage
initial_prompt = "A hungry cookie monster"
enriched_prompt, generated_image, predicted_temperature = perform_inference(initial_prompt)
print("Enriched Prompt:", enriched_prompt)
print("Predicted Temperature:", predicted_temperature)

In [ ]:
# enriched all the evaluation prompts, generate images
all_eval_prompts = df_data_samples_evaluation['Base_prompt']
all_enriched_prompts = []
all_predicted_temperatures = []
all_generated_images = []
for prompt in all_eval_prompts:
    enriched_prompt, generated_image, predicted_temperature = perform_inference(initial_prompt)
    all_enriched_prompts.append(enriched_prompt)
    all_predicted_temperatures.append(predicted_temperature)
    all_generated_images.append(generated_image)

In [ ]:
# save enrichment results
import pickle

save_path = "...."
# Save the generation results to a file
with open(save_path + 'generation_results.pkl', 'wb') as file:
    pickle.dump((all_enriched_prompts, all_predicted_temperatures, all_generated_images), file)

In [ ]:
# # Load the generation results from the file
import pickle

with open('/content/drive/Shared drives/capstone_rlt2i/Momo/eval_results/generation_results_final.pkl', 'rb') as file:
    loaded_results = pickle.load(file)

# # You can access the loaded results like this:
loaded_all_eval_prompts, loaded_all_enriched_prompts, loaded_all_predicted_temperatures, loaded_all_generated_images = loaded_results

In [ ]:
def compute_combined_score_new(text, image, w_aesthetic=0.5, w_hps=0.5):
    try:
        aesthetic_score = predict_aesthetic_score(image)
        HPS_score = hpsv2.score(image, text)
    except Exception as e:
        print(f"Error processing image: {str(e)}")
        return None

    aesthetic_score_val = aesthetic_score.cpu().item()

    # Normalize aesthetic score to be in the range [0, 1]
    aesthetic_score_normalized = aesthetic_score_val / 10.0

    # Apply power transformation to HPS score to amplify the difference between HPS scores
    HPS_score_transformed = HPS_score[0]

    # Since HPS score is already in the range [0, 1], we don't need to normalize it again
    # Calculate the combined score as a weighted sum
    combined_score = w_aesthetic * aesthetic_score_normalized + w_hps * HPS_score_transformed

    # Convert to PyTorch tensor
    combined_score_tensor = torch.tensor(combined_score, requires_grad=False).to(device)

    return combined_score_tensor

In [ ]:
wour_scores = [compute_combined_score_new(text, image[0]) for text, image in zip(loaded_all_enriched_prompts, loaded_all_generated_images)]

Aesthetic score predicted by the model:
tensor([[7.0886]], device='cuda:0', grad_fn=<AddmmBackward0>)


open_clip_pytorch_model.bin:   0%|          | 0.00/3.94G [00:00<?, ?B/s]

Download HPS_2_compressed.pt to /root/.cache/hpsv2/ sucessfully.
Aesthetic score predicted by the model:
tensor([[6.6891]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[6.5518]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[6.7331]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[5.4302]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[6.6488]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[6.5084]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[6.7119]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[6.4356]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score predicted by the model:
tensor([[7.1865]], device='cuda:0', grad_fn=<AddmmBackward0>)
Aesthetic score p

In [ ]:
reference_enriched_prompts = df_data_samples_evaluation['Prompt']
reference_images = [text_to_image_generation(reference_prompt) for reference_prompt in reference_enriched_prompts]

NameError: ignored

In [ ]:
reference_scores = [compute_combined_score_new(text, image) for text, image in zip(reference_enriched_prompts, reference_images)]

### Plot our enriched scores vs. reference enriched scores

In [ ]:
def plot_score_distribution(scores, label_text, color_code):
    # Plotting the new scores distribution with rounded scores
    plt.figure(figsize=(10, 5))
    plt.hist(scores, bins=20, alpha=0.7, color= color_code, label=label_text)
    plt.xlabel('Combined Score')
    plt.ylabel('Frequency')
    plt.title('Distribution of Combined Scores - ', label_text)
    plt.legend()
    plt.show()

In [ ]:
# Pastel Purple: #B19CD9
# Pastel Yellow: #FFFF99
# Pastel Pink: #FFD1DC

In [ ]:
plot_score_distribution(our_scores, 'RL guided enriched prompts',  '#B19CD9')

In [ ]:
plot_score_distribution(our_scores, 'Reference enriched prompts', '#FFFF99')

### Plot temperature distribution in generation

In [ ]:
def plot_temperature_distribution(temperatures, label_text, color_code):
    # Plotting the new scores distribution with rounded scores
    plt.figure(figsize=(10, 5))
    plt.hist(scores, bins=20, alpha=0.7, color= color_code, label=label_text)
    plt.xlabel('Combined Score')
    plt.ylabel('Frequency')
    plt.title('Distribution of Combined Scores - ', label_text)
    plt.legend()
    plt.show()

In [ ]:
plot_temperature_distribution(all_predicted_temperatures, 'predicted temperature distribution', '#FFD1DC')